package impledge_automation_tests;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package impledge_postman_sql;

// import org.testng.annotations.*;
// import static org.testng.Assert.*;

// public class AppTest {
//     @Test public void appHasAGreeting() {
//         // App classUnderTest = new App();
//         // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//         Test_01 test  = new Test_01();
        
        
//     }
    
//     public static void main(String[] args) {
//         new App().getGreeting();
//         Test_01();
//     }

//     private static void Test_01() {
//        
//         throw new UnsupportedOperationException("Unimplemented method 'Test_01'");
//     }
// }
